### PR TITLE
Added 'stop' command, '--config' option, and a few other options

### PR DESCRIPTION
**Pull request by AndrewMast**
What I changed:
- Upgraded Yargs to 11.0.0
- Renamed the `init` command to `configure` (but with an alias of `init` for backwards compatibility).
- Added option `force` to the `start` command.
- Added command `stop`.
- Added the `config` option to all commands.
- Added the `dir` option to all commands except `configure`.

Commands:
- `start`
  - Description: Starts the server.
  - Options: 
    - `config`: The config file to use.
    - `dir`: The working directory to use.
    - `force`: If a server is already running, stop it.
    - `dev`: Run in dev mode.
  - What happens:
    1. Checks for a `.lock` file and if the PID in it is running, throw an error (unless run with `--force`)
    2. Creates a `.lock` file and stores the PID in it.
    3. Runs the server as usual
- `stop`
  - Description: Stops the server.
  - Options:
    - `config`: The config file to use.
    - `dir`: The working directory to use.
  - What happens:
    1. Checks for a `.lock` file and if the PID in it is *not* running, throw an error
    2. Closes the PID
- `configure` (aliases: `init`)
  - Description: Creates a custom config file.
  - Options:
    - `config`: The name of the config file to create. (Default: `laravel-echo-server.json`)
  - What happens:
    1. Prompts for the settings for the config.
    2. Prompts you what you want to save the config as. (default is the `--config` option)
    3. Saves the config file.
- `client:add [id]`
  - Description: Register a client that can make api requests.
  - Options:
    - `config`: The config file to use.
    - `dir`: The working directory to use.
  - What happens:
    1. Adds a client to the config file.
- `client:remove [id]`
  - Description: Remove a registered client.
  - Options:
    - `config`: The config file to use.
    - `dir`: The working directory to use.
  - What happens:
    1. Removes client from config file.

Todo:
- Update `README.md`
- Maybe make an option to stop all running servers?

### CODE REVIEW

**Comment by AndrewMast** [comment]
This is the current output `--help`: (Notice the `server.js`)
```
Usage: server.js <command> [options]

Commands:
  server.js start          Start up the server.
  server.js stop           Stops the server.
  server.js configure      Initialize server with a config file. [aliases: init]
  server.js client:add     Register a client that can make api requests.
  server.js client:remove  Remove a registered client.

Options:
  --version   Show version number                                      [boolean]
  --help, -h  Show help                                                [boolean]

Please provide a valid command.
```

There is no "official" way to change it, but I found a way by setting `yargs.$0` to whatever you want. Which one do you prefer?

1. (A bit crowded in my opinion)
```
Usage: laravel-echo-server <command> [options]

Commands:
  laravel-echo-server start          Start up the server.
  laravel-echo-server stop           Stops the server.
  laravel-echo-server configure      Initialize server with a config file.
                                                                 [aliases: init]
  laravel-echo-server client:add     Register a client that can make api
                                     requests.
  laravel-echo-server client:remove  Remove a registered client.

Options:
  --version   Show version number                                      [boolean]
  --help, -h  Show help                                                [boolean]

Please provide a valid command.
```
2.
```
Usage: laravel-echo-server <command> [options]

Commands:
  start          Start up the server.
  stop           Stops the server.
  configure      Initialize server with a config file.           [aliases: init]
  client:add     Register a client that can make api requests.
  client:remove  Remove a registered client.

Options:
  --version   Show version number                                      [boolean]
  --help, -h  Show help                                                [boolean]

Please provide a valid command.
```

**Comment by drmmr763** [comment]
Just want throw a huge +1 at this. I am missing the `stop` command a great deal. Even stopping the server with ctrl+c seems to leave the pid around. I've been having to `kill` the pid to restart every time which is a hassle.

**Comment by AndrewMast** [comment]
@tlaverdure Could this be merged? Or are there things I need to do before that can happen?

**Comment by AndrewMast** [comment]
@tlaverdure All of the things I added are backwards compatible... I really think this could be merged...

**Comment by tlaverdure** [comment]
@AndrewMast sorry for the delay on this! Been busy with work stuff...

This seems like  a great idea. There were some changes made along the way to add config options from the .env file that I think are conflicting with your CLI changes. Can you take a look at those conflicts so we can get this merged?

**Comment by AndrewMast** [comment]
@tlaverdure Sure, I haven't looked at the code in a while but I will try to do it within the next few days.

**Comment by tlaverdure** [comment]
Thanks! Published as 1.5.0.

**Pull request merged**
