### PR TITLE
Enable receiving requests from Echo client

### PR DESCRIPTION
**Pull request by 1618033**
Already submitted pull request for corresponding enablements in Echo client

### CODE REVIEW

**Comment by zdenektopic** [comment]
how does this look? i would love to see this feature implemented as I would use it right away

**Comment by barryvdh** [comment]
The corresponding PR is not actually accepted right, so does this PR still work?

**Comment by 1618033** [comment]
I believe that there have been major changes on the master, so I wouldn't
expect for this to be mergeable any longer.

**Comment by barryvdh** [comment]
And isn't it just as easy to just send an XHR request to the server directly?

**Comment by tlaverdure** [comment]
Closing since https://github.com/tlaverdure/laravel-echo-server/pull/100 is doing the same and is up to date.

**Pull request closed without merging**
