### PR TITLE
Clear error messages for authenticating

### PR DESCRIPTION
**Pull request by barryvdh**
This adds extra error handling to the authentication process.

 - Fix typo in ServerRequest
 - Difference between error (eg. invalid url) or invalid response (eg. not authenticated or error 500)
 - Show authentication message in dev mode for succes + fail
 - Show response when unauthenticated, to see what is wrong (eg. internal error or ..)

### CODE REVIEW

**Comment by kkomelin** [comment]
You've done a great job. Thank you.
I actually spent much time trying to figure out why my authentication didn't work.

**Comment by bodonb** [comment]
I got this error:
```
could not be authenticated for private-message-received
Unauthorized.
Client can not be authenticated, got HTTP status 401
```
I use this in BroadcastServiceProvider:
`Broadcast::routes(['middleware' => ['auth', 'web']]);`

**Comment by barryvdh** [comment]
Much better, right? :)

**Comment by bodonb** [comment]
Yeah its better :-) but i follow the laravel.com description and it does not work.

**Comment by barryvdh** [comment]
Please create a separate issue for that than.

**Comment by tlaverdure** [comment]
Thanks

**Pull request merged**
