### PR TITLE
Send leave message on actual leaving

### LINKED ISSUE #67: left channel after join
I run this code in js console:

```
    window.Echo.channel('tickets')
            .listen('ticket.created', function(e){
                console.log(e.order.name);
            });
```

and see this in laravel-echo-server cli:

```
$ laravel-echo-server start

L A R A V E L  E C H O  S E R V E R

⚠Starting server in DEV mode...

✔ Running at localhost on port 6001
✔ Channels are ready.
✔ Listening for http events...
✔ Listening for redis events...

Server ready!

[18:04:10] - S8LMlDg5BngTibDtAAAB joined channel: tickets
[18:04:10] - S8LMlDg5BngTibDtAAAB left channel: tickets
```

laravel-echo-server.json:

```
{
	"appKey": "myAppKeyFrom.env",
	"authHost": "http://localhost/",
	"authEndpoint": "/broadcasting/auth",
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"host": "localhost",
			"port": 6379,
			"db": 0
		}
	},
	"devMode": true,
	"host": "localhost",
	"port": "6001",
	"referrers": [
	],
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"verifyAuthPath": true,
	"verifyAuthServer": false
}
```

bootstrap.js

```
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost:6001'
});
```

### PR DESCRIPTION
**Pull request by barryvdh**
Put the notify INSIDE the leave callback, otherwise it's shown directly.
Fixes #67, see https://github.com/tlaverdure/laravel-echo-server/issues/67#issuecomment-271614146

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
It would be really nice if this could be merged!

Thank you!

**Comment by barryvdh** [comment]
Actually, I put the message on the leave function, as that is also called on unsubscribe.

Problem is that the disconnect event listener needs to be removed after leaving a room. 

If you do this:
 - subscribe
 - unsubscribe
 - disconnect

leave() is actually triggered twice. Besides a confusing message, this also leaves the event listener attached for all channels.

I added an on() and unbind() method, similar to that in laravel-echo, to remembers even listeners. Upon leaving, we can remove all listeners so we only trigger the message once and don't keep remembering old listeners..

**Comment by barryvdh** [comment]
Sorry to keep changing around on this, but I think it makes more sense to just call our channel `leave` method on disconnect (`disconnecting` actually, because then we still have the rooms property). This way both unsubscribe and disconnect behave the same and we have just 1 listener for each socket, not one for each channel per socket.

**Comment by barryvdh** [comment]
Added the reason why someone left (unsubscribed, transport closed etc)

**Comment by tlaverdure** [comment]
Thanks

**Pull request merged**
