### PR TITLE
Add hooks feature to listen to client-side event

### PR DESCRIPTION
**Pull request by alexxiyang**
Add hookHost, hooks.onJoinEndpoint, hooks.onLeaveEndpoint, hooks.onClientEventEndpoint to `laravel-echo-server.json`. Implement client-side event hooks so that the server-side can listen to client-side event.

### CODE REVIEW

**Comment by alexxiyang** [comment]
@tlaverdure Could you help to review this pull request?

**Comment by zek** [comment]
Any updates on this PR? This is the feature what I need.

**Comment by alexxiyang** [comment]
This is the feature which pusher already has. I hope someone can help to review and merge this pull request

**Comment by alexxiyang** [comment]
There is a feature called webhook in `Pusher`: https://pusher.com/docs/webhooks
By using webhook we can notify server side that something is happening , for example: someone is leaving this channel because he/she directly close the tab or browser. This pr provide the same feature like pusher webhook

**Comment by zek** [comment]
@alexxiyang Right now I am using modified version of your PR. I also need to save data sent with whisper command.

**Comment by Ifnot** [comment]
It will be welcome to improve the hook list on the upcoming plugin system #285 :)

**Comment by alexxiyang** [comment]
@zek I guess I should send the `data.data` in `clientEvent(socket, data): void` so that you can get the payload of whisper event, right?
If that so, I've already committed some changes to support whisper event. Once this PR has been approved, I will create another PR to cover it. check this out:

```javascript
    /**
     * Prepare headers for request to app server.
     * 
     * @param {any} socket
     * @param {any} auth
     * @param {string} channel
     * @param {string} hookEndpoint
     * @param {any} payload
     * @returns {any}
     */
    prepareHookHeaders(socket: any, auth: any, channel: string, hookEndpoint: string, payload: any): any {
        let options = {
            url: this.options.hookHost + hookEndpoint,
            form: { channel_name: channel, payload: payload },
            headers: (auth && auth.headers) ? auth.headers : {}
        };
        options.headers['Cookie'] = socket.request.headers.cookie;
        options.headers['X-Requested-With'] = 'XMLHttpRequest';
        return options;
    }
```

Do you know if there is a way to put more commits in this PR without creating another PR?

**Comment by zek** [comment]
@alexxiyang looks perfect. That is what I needed.

There is one more thing I want to ask. Are we able to get user in laravel via $request->user()

When I check it first time, as I remember it was working for joinChannel.

**Comment by zek** [comment]
My endpoints don't require CSRF token. We can also disable it by defining some exceptions in VerifyCsrfToken. So that wont be a problem.

I am using laravel passport and using echo on my mobile application. So I authorize users with header "Authorization:  Bearer skti68i... "

**Comment by alexxiyang** [comment]
@zek I have to apologize for my comment before. `$request->user()` is nothing to do with CSRF token at all. It's about `laravel_session` cookie value. Let's take a look about the implement of `$request->user()`

Here is the implement of `$request->user()`:
```php
public function user($guard = null)
{
    return call_user_func($this->getUserResolver(), $guard);
}
```

as you can see `user()` function actually call `getUserResolver()` directly. `userResolver` is set by `AuthServiceProvider.registerRequestRebindHandler`:

```php
protected function registerRequestRebindHandler()
{
    $this->app->rebinding('request', function ($app, $request) {
        $request->setUserResolver(function ($guard = null) use ($app) {
            return call_user_func($app['auth']->userResolver(), $guard);
        });
    });
}
```

`$app['auth']` is an `instance of Illuminate\Auth\AuthManager`.  `AuthManager` set `userResolver` in the `__construct`:

```php
public function __construct($app)
{
    $this->app = $app;

    $this->userResolver = function ($guard = null) {
        return $this->guard($guard)->user();
    };
}
```

`$this->guard($guard)` give you an instance of `SessionGuard`. And here is the code of how you really get an user in `SessionGuard`:

```php
public function user()
{
    if ($this->loggedOut) {
        return;
    }

    // If we've already retrieved the user for the current request we can just
    // return it back immediately. We do not want to fetch the user data on
    // every call to this method because that would be tremendously slow.
    if (! is_null($this->user)) {
        return $this->user;
    }
   // ......
}
```

OK, so as you can see `$request->user()` helps you to get user from session. We does have `laravel_session` value in `cookie` when user leaving the channel. So we can add `EncryptCookies` and `StartSession` into your middleware groups. For example, I put my leave channel endpoint in `api` group like this:

```php
Route::post('/leaveChannel', function (Request $request) {
	Log::info("someone is leaving");
}
```

I put these 2 middlewares into `/app/Http/Kernal.php` as below:
```php
'api' => [
    // put these 2 middleware to get user from session in controller
    \App\Http\Middleware\EncryptCookies::class,
    \Illuminate\Session\Middleware\StartSession::class,

    // the existing middleware which i have before, just leave them without any change.
    'throttle:60,1',
    'bindings',

],
```

OK, let's test if we can get user in leave channel endpoint
```php
Route::post('/leaveChannel', function (Request $request) {
	Log::info("someone is leaving");

	// try to get user
	$user = $request->user();
    Log::info("user: {$user->name} is leaving");
}
```

Here you go 
```
[2018-11-13 22:22:59] staging.INFO: someone is leaving  
[2018-11-13 22:22:59] staging.INFO: user: test2 is leaving 
```

**Comment by alexxiyang** [comment]
@tlaverdure any updates?

**Comment by alexxiyang** [comment]
@tlaverdure Yeah... I think they can be sent to one endpoint, but I think multiple hook endpoint will give benefits to code decoupling. So...what do you think?

**Comment by alexxiyang** [comment]
@tlaverdure any updates?

**Comment by zek** [comment]
@alexxiyang I didn't have time to test what you write about session. I will look at it this weekend.

I think, collecting all events to only one endpoint is better. 

I agree with you about increasing difficulty of deployment. I have same reason to not use it for now.

**Comment by zek** [comment]
It would be nice if we create field in .env for HookHost like below

https://github.com/zek/laravel-echo-server/blob/master/src/cli/cli.ts#L74

**Comment by zek** [comment]
@alexxiyang I just tested it and it didnt work. This is what I get on leave event

image

And this is on join. I can authorize user because there is authorization token.

image

I get no session_token. I tried your middleware solution (StartSession, EncryptCookies) but it doesn't work.

I guess the reason is my client never sends session because it never had. I authorize users with bearer token.

**Comment by alexxiyang** [comment]
@zek Yeah, you are right. If you haven't signed in before then you wouldn't have session. I guess the best way to get user for you in this case is adding your middleware to obtain user via `authorization` which is exactly the way I'm using right now.

**Comment by tomonsoejang** [comment]
Is there a mechanism to identify between browser reload and closing the browser?

**Comment by alexxiyang** [comment]
I don't know how to add commit to this PR. So I will close this PR first and then create another PR

**Pull request closed without merging**
